language: go
go:
  - 1.7
before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y && sudo apt-get update
install:
  - sudo sudo apt-get install glide
script:
  - go test -v $(glide novendor)
